Support MultiValueDict in filtering.
idlesign/django-siteforms pull request #14
Opened 2023-09-06 14:16 UTC by questonit

Support filtering of one field with two multiple filters.

2023-09-07 01:25 UTC, idlesign requested changes

2023-09-07 01:25 UTC, idlesign commented on siteforms/base.py
> +    """Allows setting the ratio of the field in the form to the field in the database.
Ratio это отношение в мат. смысле, тут нужен mapping.

2023-09-07 01:25 UTC, idlesign commented on siteforms/base.py
> +        for key, value_list in data.lists():
Судя по разметке, в data может приходить словарь, а у него нет .lists().
Если свести к единому типу не получится, то тут, видимо, нужна будет спец. обработка.

2023-09-07 10:59 UTC, questonit commented on siteforms/base.py
> +        for key, value_list in data.lists():
Тогда преобразуем data в `MultiValueDict`. Словарь спокойно преобразуется, а `QueryDict` и так наследуется от MultiValueDict.  Проверки `if not isinstance(data, MultiValueDict)` должно быть достаточно.

Тогда тут при приобразовании из dict в цикле в value_list может лежать неитерируемый объект (например, число). Добавлю:
```
if not isinstance(value_list, list):
                value_list = [value_list]
```
Это же будет полезно, если в value_list будет лежать строка со * внутри ('abc*' преобразовалось бы в ['a', 'b', 'c', что неверно)

2023-09-08 08:54 UTC, merged

2023-09-08 08:54 UTC, idlesign commented
Thank you. Merged.